Adds fix for MapTR model  Dynamo tracing with TorchRuntimeError (#551)
### Ticket
[Link to Github
Issue](https://github.com/tenstorrent/tt-xla/issues/4013)

### Problem description
- MapTR model fails immediately during Dynamo tracing with
`TorchRuntimeError` before any model computation begins -
[maptr_tiny_fusion_trace_issue.log](https://github.com/user-attachments/files/26231495/maptr_tiny_fusion_trace_issue.log)

- Error
```
torch._dynamo.exc.TorchRuntimeError: Dynamo failed to run FX node with fake tensors: call_function <Wrapped method <original reciprocal>>(*(FakeTensor(..., size=(), dtype=torch.int64),), **{}): got AttributeError("'ndarray' object has no attribute 'reciprocal'")
```

### What's changed

- MapTR model was failing immediately during Dynamo tracing with
TorchRuntimeError before any model computation began, traced to np.prod
in the sparity property returning a NumPy ndarray instead of a PyTorch
tensor, causing .reciprocal() to fail
- Fixed by replacing with torch.prod(torch.tensor(self.spatial_shape))

### Checklist
- [x] New/Existing tests provide coverage for changes