Pinned transformers version for GLM model (#569)
Ref : [Error in
CI](https://github.com/tenstorrent/tt-xla/actions/runs/24019688703/job/70047925733)

### Problem description
GLM model is facing an error in main because of transformers version
uplift

### What's changed
```
 RuntimeError: Failed to import easydel.modules.auto because of the following error (look up to see its traceback):
cannot import name 'download_url' from 'transformers.utils' 
```
The above error is faced from latest transformers version
* pinned transformers version as 4.57.1 in requirements file