Rename gliner to gliner_model to avoid import error from test_models.py in tt-torch
  ImportError: cannot import name 'GLiNER' from partially initialized
  module 'gliner' (most likely due to a circular import)